# Generated by Django 4.1.2 on 2023-02-25 18:22

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_homework_student_course_finished_subscription_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='avatar',
            field=models.ImageField(blank=True, upload_to=core.models.avatar_upload_to),
        ),
    ]
