# Generated by Django 4.1.2 on 2023-03-09 19:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_student_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='role',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='core.role'),
            preserve_default=False,
        ),
    ]
