# Generated by Django 4.1.2 on 2023-03-18 17:53

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_student_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='avatar',
            field=models.ImageField(blank=True, default='avatar/default.png', upload_to=core.models.avatar_upload_to),
        ),
    ]
